### ISSUE TITLE
Djangorestframework 3.7.X powoduje błąd w testach

### ISSUE THREAD

**Issue by kbiernat** [watchdogpolska/feder#379]
Po podniesieniu djangorestframework do 3.7.X testy nie przechodzą z poniższym błędem:
```pytb
Traceback (most recent call last):
  File "/home/travis/build/watchdogpolska/feder/feder/main/mixins.py", line 203, in test_status_code_for_signed_user
    response = self.client.get(self.get_url())
  File "/home/travis/build/watchdogpolska/feder/feder/alerts/tests.py", line 57, in get_url
    return reverse('alerts:delete', kwargs={'pk': self.alert.pk})
  File "/home/travis/build/watchdogpolska/feder/.tox/py27-dj110/lib/python2.7/site-packages/django/urls/base.py", line 87, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
NoReverseMatch: u'pl' is not a registered namespace
```
Vide: https://travis-ci.org/watchdogpolska/feder/jobs/315419189

**Comment by ad-m** [comment]
Ten komunikat mi się kojarzy z problemem z importowaniem urli, albo z zbyt wczesnym odwołaniem do urli. Generalnie chyba coś zmieniło się w sposobie budowania ```urlpatterns```. Zawsze mam problem z debugowaniem tego, pewnie najprościej będzie zrobić bisekcje i wyłapać w którym momencie w djangorestframework to się zmieniło.
