### ISSUE TITLE
Wyszukiwanie podobnych pism - problemy wydajnościowe

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/feder#822]
W Fedrowaniu mamy mechanizm wyszukiwania podobnych pism. Niemal cały zamknięty w https://github.com/watchdogpolska/feder/tree/master/feder/es_search . 

Został on wyłączony, bo powodował on wydłużenie czasu odpowiedzi, gdy wyświetlaliliśmy podobne listy. Przyczyna nie była możliwa do samodzielnej diagnozy. Od czego mamy zacząć?

**Comment by ad-m** [comment]
Sprawdziłem na kolejce workera. Tam także błędy. Przykładowo:

```
Traceback (most recent call last):
  File "/opt/feder/releases/releases/20200919144259/env/lib/python3.6/site-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/opt/feder/releases/releases/20200919144259/src/feder/es_search/tasks.py", line 11, in index_letter
    delete_document(letter.pk)
  File "/opt/feder/releases/releases/20200919144259/src/feder/es_search/queries.py", line 19, in delete_document
    LetterDocument.search().query(Q("match", letter_id=letter_id)).delete()
  File "/opt/feder/releases/releases/20200919144259/env/lib/python3.6/site-packages/elasticsearch_dsl/search.py", line 742, in delete
    es.delete_by_query(index=self._index, body=self.to_dict(), **self._params)
  File "/opt/feder/releases/releases/20200919144259/env/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 152, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/opt/feder/releases/releases/20200919144259/env/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 712, in delete_by_query
    body=body,
  File "/opt/feder/releases/releases/20200919144259/env/lib/python3.6/site-packages/elasticsearch/transport.py", line 392, in perform_request
    raise e
  File "/opt/feder/releases/releases/20200919144259/env/lib/python3.6/site-packages/elasticsearch/transport.py", line 365, in perform_request
    timeout=timeout,
  File "/opt/feder/releases/releases/20200919144259/env/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 257, in perform_request
    raise ConnectionTimeout("TIMEOUT", str(e), e)
elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='helper.watchdog.internal', port=9200): Read timed out. (read timeout=10))
```

**Comment by PiotrIw** [comment]
Elasticserach jest do wyłączenia. Zasoby sprzętowe serwera helper dedykowane do obsługi ES musiałyby być powiększone kilkukrotnie (ilość procesorów i pamięci) żeby ES działał sprawnie nawet na mniejszej bazie niż obecne ~170k maili. Wymagania dla naszych potrzeb (~200k dokumentów po 2-3kB, do 3 workerów) to 4-8 rdzeni i 8-16GB RAM. helper ma 2 rdzenie i 4GB RAM, stąd timeouty przy praktycznie każdym wyszukiwaniu.  ES to narzędzie dla dużych systemów.

@AgnieszkaZdanowicz @dzemeuksis @mrbojko - jaka jest potrzeba z tym wyszukiwnaiem w mailach? Pomyślę jak ją zaspokoić, a ES wyłączę w którejś kolejnej wersji federa.

**Comment by AgnieszkaZdanowicz** [comment]
@PiotrIw ja nie wiem za bardzo, jaki był cel wyszukiwania tych podobnych odpowiedzi, więc ja tu żadnej potrzeby nie mam

**Comment by PiotrIw** [comment]
Elastic search wyłączony w v1.4.02
